[env]
BEVY_ASSET_ROOT = "."

[alias]
rc = 'run --bin client'
rs = 'run --bin server'
tc = 'run --bin client --features bevy/trace_tracy'
ts = 'run --bin server --features bevy/trace_tracy'
t = 'test'
